AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Story Forge MVP
Resources:
  StoryForgeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
  StoryForgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: handler.lambda_handler
      CodeUri: ../backend/
      MemorySize: 512
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StoryForgeBucket
      Events:
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref StoryForgeApi
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref StoryForgeBucket
          IMAGE_BUCKET_NAME: !Ref StoryForgeBucket
  StoryForgeBucket:
    Type: AWS::S3::Bucket
Outputs:
  ApiUrl:
    Value: !Sub "https://${StoryForgeApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
